name: hospitals-access-peru
channels:
  - conda-forge
dependencies:
  - python=3.9 
  - streamlit
  - pandas
  - numpy
  - geopandas  # Primera dependencia geoespacial
  - folium     # <--- ASEGÚRATE DE QUE ESTÉ AQUÍ
  - fiona
  - shapely
  - pyproj
  - matplotlib
  # ... otras librerías